#!/usr/bin/env python3
"""Guard the Lean proof spine's axiom budget mechanically.

Runs `#print axioms` on a curated list of headline theorems (see
`formal/axiom-ledger.json`), diffs the result against the checked-in ledger,
and (re)generates `metadata/axiom-budget-index.tex` for Appendix G. Any silent
change in what a headline theorem ultimately rests on -- an accidentally
added `MB*` bridge, a stray global axiom, a widened carrier assumption -- is
caught here instead of only showing up as prose drift.

Usage (from anywhere in the repo):
    cd formal && lake build          # first time / after editing spine .lean files
    python3 scripts/check_axiom_budget.py            # check only, exit 1 on drift
    python3 scripts/check_axiom_budget.py --update   # accept current output as new ledger
    python3 scripts/check_axiom_budget.py --no-lean  # regenerate the .tex table from the
                                                       # existing ledger without invoking lean
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

FORMAL_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = FORMAL_ROOT.parent
LEDGER_PATH = FORMAL_ROOT / "axiom-ledger.json"
TEX_OUT = REPO_ROOT / "metadata" / "axiom-budget-index.tex"

NAMESPACE = "AlignmentProofSpine"
CORE_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}
BRIDGE_RE = re.compile(rf"^{re.escape(NAMESPACE)}\.MB\d")
ALL_CORE_BRIDGES = {
    "MB1_estimator_soundness",
    "MB3_bearer_import",
    "MB4_correction_legitimacy",
    "MB5_ontology_shift_successor_audit",
    "MB6a_percolation_evidence_to_basin_stability",
    "MB6b_basin_stability_to_correction_integrity",
    "MB7a_access_model_soundness",
    "MB7b_filter_family_coverage",
    "MB7c_hidden_biq_to_adversarial_robustness",
    "MB7d_inferential_uad_detector_soundness",
    "MB8_cev_process_convergence",
    "MB9_grounding_certificate_soundness",
}
# MB10 (`AlignmentProofSpine.Forgeability`) is not a `Core.BridgeAssumptions`
# field -- see that module's docstring -- so it is not part of `standardBridges`
# and never joins `ALL_CORE_BRIDGES`'s "All MB1--MB9" theorems. It gets its own
# collapse case below in case a future theorem invokes all ten.
ALL_BRIDGES_WITH_MB10 = ALL_CORE_BRIDGES | {"MB10_conserved_property_signature_not_forged"}

DEPENDS_RE = re.compile(
    r"'([\w.]+)' depends on axioms: \[(.*?)\]", re.DOTALL
)
NO_AXIOMS_RE = re.compile(r"'([\w.]+)' does not depend on any axioms")

TEX_HEADER = """\
% AUTO-GENERATED by formal/scripts/check_axiom_budget.py -- do not edit by hand.
% Source: formal/axiom-ledger.json (refreshed via `#print axioms` on each theorem below).
% Regenerate: make generate or ./scripts/generate_manuscript_tex.sh
"""


def load_ledger() -> dict:
    with LEDGER_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def short_name(qualified: str) -> str:
    prefix = NAMESPACE + "."
    return qualified[len(prefix):] if qualified.startswith(prefix) else qualified


def run_print_axioms(names: list[str]) -> dict[str, list[str]]:
    lines = [f"import {NAMESPACE}", f"open {NAMESPACE}"]
    lines += [f"#print axioms {short_name(n)}" for n in names]
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".lean", delete=False, dir=FORMAL_ROOT
    ) as fh:
        fh.write("\n".join(lines) + "\n")
        scratch_path = Path(fh.name)
    try:
        proc = subprocess.run(
            ["lake", "env", "lean", str(scratch_path)],
            cwd=FORMAL_ROOT,
            capture_output=True,
            text=True,
            timeout=300,
        )
    finally:
        scratch_path.unlink(missing_ok=True)

    if proc.returncode != 0:
        print(proc.stdout, file=sys.stderr)
        print(proc.stderr, file=sys.stderr)
        raise SystemExit(
            "ERROR: `lake env lean` failed -- run `cd formal && lake build` first."
        )

    out = proc.stdout
    results: dict[str, list[str]] = {}
    for match in DEPENDS_RE.finditer(out):
        name, body = match.group(1), match.group(2)
        axioms = [a.strip().rstrip(",") for a in body.split(",")]
        axioms = [a for a in axioms if a]
        results[name] = sorted(axioms)
    for match in NO_AXIOMS_RE.finditer(out):
        results[match.group(1)] = []

    missing = [n for n in names if n not in results]
    if missing:
        raise SystemExit(
            "ERROR: could not parse #print axioms output for: "
            + ", ".join(missing)
            + f"\n--- raw output ---\n{out}"
        )
    return results


def classify(axiom: str) -> str:
    if axiom in CORE_AXIOMS:
        return "core"
    if BRIDGE_RE.match(axiom):
        return "bridge"
    return "vocabulary"


def diff_report(ledger_entries: list[dict], actual: dict[str, list[str]]) -> list[str]:
    problems: list[str] = []
    for entry in ledger_entries:
        name = entry["name"]
        expected = set(entry["axioms"])
        got = set(actual[name])
        added = sorted(got - expected)
        removed = sorted(expected - got)
        if added or removed:
            problems.append(f"{name}:")
            for a in added:
                problems.append(f"    + {a}  ({classify(a)})")
            for r in removed:
                problems.append(f"    - {r}  ({classify(r)})")
    return problems


def bridge_list(axioms: list[str]) -> str:
    bridges = sorted(short_name(a) for a in axioms if classify(a) == "bridge")
    if not bridges:
        return "---"
    bridge_set = set(bridges)
    if bridge_set == ALL_BRIDGES_WITH_MB10:
        return "All \\texttt{MB1}--\\texttt{MB10}"
    if bridge_set == ALL_CORE_BRIDGES:
        return "All \\texttt{MB1}, \\texttt{MB3}--\\texttt{MB9}"
    return ", ".join(rf"\leanid{{{b}}}" for b in bridges)


def latex_escape(text: str) -> str:
    for old, new in (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("#", r"\#"),
        ("_", r"\_"),
    ):
        text = text.replace(old, new)
    return text


def render_tex(ledger_entries: list[dict]) -> str:
    header_row = r"\textbf{Theorem} & \textbf{Bridges used} & \textbf{Gloss} & \textbf{Core} & \textbf{Vocab.} \\"
    lines = [
        TEX_HEADER.rstrip(),
        "",
        r"\begin{longtable}{@{}p{0.23\linewidth}p{0.19\linewidth}p{0.28\linewidth}rr@{}}",
        r"\caption{Axiom budget for headline proof-spine theorems, mechanically checked "
        r"against \texttt{formal/axiom-ledger.json} by "
        r"\texttt{formal/scripts/check\_axiom\_budget.py}.}"
        r"\label{tab:appi-axiom-budget}\\",
        r"\toprule",
        header_row,
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        header_row,
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for entry in ledger_entries:
        name = short_name(entry["name"])
        axioms = entry["axioms"]
        core_n = sum(1 for a in axioms if classify(a) == "core")
        vocab_n = sum(1 for a in axioms if classify(a) == "vocabulary")
        bridges = bridge_list(axioms)
        gloss = latex_escape(entry["gloss"])
        lines.append(rf"\leanid{{{name}}} & {bridges} & {gloss} & {core_n} & {vocab_n} \\")
    lines.append(r"\end{longtable}")
    lines.append("")
    lines.append(
        r"\emph{Core} = Lean/Mathlib axioms (\texttt{propext}, \texttt{Classical.choice}, "
        r"\texttt{Quot.sound}). \emph{Bridges used} lists which of \texttt{MB1}--\texttt{MB11} "
        r"(with lettered sub-bridges \texttt{MB4a}, \texttt{MB6a}/\texttt{MB6b}, "
        r"\texttt{MB7a}--\texttt{MB7d}) "
        r"the theorem actually invokes; ``---'' means none (bridges are either absent or "
        r"supplied as an explicit hypothesis rather than a global axiom, as in "
        r"\leanid{certified_class_safety_from_bridge_record}). \texttt{MB4a} (measured-path "
        r"legitimacy, incl.\ anti-capture), \texttt{MB10} (successor forgeability), and "
        r"\texttt{MB11} (safety-case adequacy) are declared "
        r"outside \texttt{Core.BridgeAssumptions} and so "
        r"never appear bundled into an ``All \texttt{MB1}--\texttt{MB9}'' cell. The "
        r"statement-bearing imported field theorem "
        r"\leanid{OA2016_offpolicy_qlearning_convergence} (with its opaque condition "
        r"predicate \leanid{OAConvergenceConditions}) is counted under \emph{Vocab.}, which "
        r"otherwise counts declared carriers/predicates (e.g.\ \texttt{System}, "
        r"\texttt{CCIPreserved}) that are axiomatized as abstract vocabulary, not proved."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="rewrite the ledger from current lean output")
    parser.add_argument("--no-lean", action="store_true", help="skip lean invocation; regenerate .tex from ledger only")
    args = parser.parse_args()

    ledger = load_ledger()
    entries = ledger["theorems"]

    if args.no_lean:
        TEX_OUT.write_text(render_tex(entries), encoding="utf-8")
        print(f"Wrote {TEX_OUT.relative_to(REPO_ROOT)} from existing ledger (lean not invoked).")
        return 0

    names = [e["name"] for e in entries]
    actual = run_print_axioms(names)

    if args.update:
        for entry in entries:
            entry["axioms"] = actual[entry["name"]]
        with LEDGER_PATH.open("w", encoding="utf-8") as fh:
            json.dump(ledger, fh, indent=2)
            fh.write("\n")
        TEX_OUT.write_text(render_tex(entries), encoding="utf-8")
        print(f"Updated {LEDGER_PATH.relative_to(REPO_ROOT)} and {TEX_OUT.relative_to(REPO_ROOT)} "
              f"from current lean output ({len(entries)} theorems).")
        return 0

    problems = diff_report(entries, actual)
    if problems:
        print("Axiom budget drift detected (ledger vs. current lean output):", file=sys.stderr)
        for line in problems:
            print(f"  {line}", file=sys.stderr)
        print(
            "\nIf this drift is intentional, review it and rerun with --update to "
            "accept it into formal/axiom-ledger.json.",
            file=sys.stderr,
        )
        return 1

    TEX_OUT.write_text(render_tex(entries), encoding="utf-8")
    print(
        f"Axiom budget check passed ({len(entries)} theorems, no drift). "
        f"Wrote {TEX_OUT.relative_to(REPO_ROOT)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
