#!/usr/bin/env python3
"""Generate LaTeX roadmap tables from metadata/book.yml and parts/*.tex."""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOOK_YML = ROOT / "metadata" / "book.yml"
PARTS_DIR = ROOT / "parts"
TABLES_DIR = ROOT / "tables"

ROMANS = ("I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X")

GENERATED_HEADER = """\
% AUTO-GENERATED by scripts/generate_tables.py — do not edit by hand.
% Sources: metadata/book.yml, parts/part*.tex
% Regenerate: ./build.sh or python3 scripts/generate_tables.py
"""


@dataclass(frozen=True)
class ChapterEntry:
    chapter_id: str
    title: str
    status: str
    part_index: int
    part_title: str
    order: int


def latex_escape(text: str) -> str:
    replacements = (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("#", r"\#"),
        ("_", r"\_"),
    )
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def parse_book_yml(path: Path) -> tuple[dict[str, dict[str, str]], dict[str, dict[str, str]]]:
    chapters: dict[str, dict[str, str]] = {}
    parts: dict[str, dict[str, str]] = {}
    section: str | None = None
    current: str | None = None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if line == "chapters:":
            section = "chapters"
            current = None
            continue
        if line == "parts:":
            section = "parts"
            current = None
            continue
        if not line.startswith("  ") or section is None:
            continue

        key_match = re.match(r"^  ([A-Za-z0-9]+):\s*$", line)
        if key_match:
            current = key_match.group(1)
            if section == "chapters":
                chapters[current] = {}
            else:
                parts[current] = {}
            continue

        if current is None:
            continue

        field_match = re.match(r'^    (\w+): "(.*)"\s*$', line)
        if field_match:
            field, value = field_match.groups()
            if section == "chapters":
                chapters[current][field] = value
            else:
                parts[current][field] = value
            continue

        bare_match = re.match(r"^    (\w+): (\S+)\s*$", line)
        if bare_match:
            field, value = bare_match.groups()
            if section == "chapters":
                chapters[current][field] = value

    return chapters, parts


def chapter_id_from_input(slug: str) -> str:
    match = re.match(r"(ch\d+b?)", slug)
    if not match:
        raise ValueError(f"Cannot derive chapter id from input slug: {slug}")
    return match.group(1)


def parse_part_file(path: Path) -> tuple[str, list[str]]:
    text = path.read_text(encoding="utf-8")
    title_match = re.search(r"\\part\{([^}]+)\}", text)
    if not title_match:
        raise ValueError(f"No \\part{{...}} title found in {path}")
    title = title_match.group(1)
    slugs = re.findall(r"\\input\{chapters/(ch[^}]+)\}", text)
    if not slugs:
        raise ValueError(f"No chapter \\input lines found in {path}")
    chapter_ids = [chapter_id_from_input(slug) for slug in slugs]
    return title, chapter_ids


def chapter_display_id(chapter_id: str) -> str:
    if chapter_id == "ch39b":
        return "39b"
    return str(int(chapter_id[2:]))


def load_manuscript() -> tuple[list[ChapterEntry], dict[str, dict[str, str]], list[Path]]:
    chapters_meta, parts_meta = parse_book_yml(BOOK_YML)
    part_files = sorted(PARTS_DIR.glob("part*.tex"))
    if len(part_files) != 10:
        raise ValueError(f"Expected 10 part files, found {len(part_files)}")

    entries: list[ChapterEntry] = []
    order = 0
    for part_index, part_file in enumerate(part_files, start=1):
        part_key = f"part{part_index:02d}"
        part_title, chapter_ids = parse_part_file(part_file)
        for chapter_id in chapter_ids:
            meta = chapters_meta.get(chapter_id)
            if meta is None:
                raise KeyError(f"{chapter_id} listed in {part_file.name} but missing from book.yml")
            if "title" not in meta or "status" not in meta:
                raise KeyError(f"{chapter_id} in book.yml is missing title or status")
            order += 1
            entries.append(
                ChapterEntry(
                    chapter_id=chapter_id,
                    title=meta["title"],
                    status=meta["status"],
                    part_index=part_index,
                    part_title=part_title,
                    order=order,
                )
            )
        if part_key not in parts_meta or "summary" not in parts_meta[part_key]:
            raise KeyError(f"{part_key} missing summary in metadata/book.yml parts section")

    listed = {entry.chapter_id for entry in entries}
    extra = sorted(set(chapters_meta) - listed)
    if extra:
        raise ValueError(f"book.yml chapters not included in any part file: {', '.join(extra)}")

    return entries, parts_meta, part_files


def format_chapter_range(start: int, end: int) -> str:
    if start == end:
        return str(start)
    return f"{start}--{end}"


def write_chapter_map(entries: list[ChapterEntry]) -> None:
    lines = [
        GENERATED_HEADER.rstrip(),
        r"\begin{longtable}{@{}clll@{}}",
        r"\toprule",
        r"\textbf{Ch.} & \textbf{Part} & \textbf{Title} & \textbf{Status} \\",
        r"\midrule",
        r"\endhead",
    ]
    for entry in entries:
        lines.append(
            " & ".join(
                [
                    chapter_display_id(entry.chapter_id),
                    ROMANS[entry.part_index - 1],
                    latex_escape(entry.title),
                    entry.status,
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    (TABLES_DIR / "chapter-map.tex").write_text("\n".join(lines), encoding="utf-8")


def write_part_roadmap(
    entries: list[ChapterEntry],
    parts_meta: dict[str, dict[str, str]],
    part_files: list[Path],
) -> None:
    lines = [GENERATED_HEADER.rstrip(), r"\begin{description}[style=nextline]"]

    for part_index, part_file in enumerate(part_files, start=1):
        part_key = f"part{part_index:02d}"
        part_title, chapter_ids = parse_part_file(part_file)
        part_entries = [e for e in entries if e.chapter_id in chapter_ids]
        start = part_entries[0].order
        end = part_entries[-1].order
        summary = parts_meta[part_key]["summary"]
        roman = ROMANS[part_index - 1]
        ch_range = format_chapter_range(start, end)

        lines.append(
            rf"\item[\textbf{{Part~{roman} --- {latex_escape(part_title)}}}] "
            rf"Chs.~{ch_range}. {latex_escape(summary)}"
        )

    lines.extend([r"\end{description}", ""])
    (TABLES_DIR / "part-roadmap.tex").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    try:
        entries, parts_meta, part_files = load_manuscript()
    except (KeyError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    write_chapter_map(entries)
    write_part_roadmap(entries, parts_meta, part_files)
    print(
        f"Generated tables/chapter-map.tex and tables/part-roadmap.tex "
        f"({len(entries)} chapters, 10 parts)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
