#!/usr/bin/env python3
"""Generate Appendix E assumptions index from metadata/assumptions-ledger.md."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEDGER_MD = ROOT / "metadata" / "assumptions-ledger.md"
OUT = ROOT / "metadata" / "assumptions-index.tex"
CHAPTERS_DIR = ROOT / "chapters"

HEADER = """\
% AUTO-GENERATED by scripts/generate_assumptions_appendix.py — do not edit by hand.
% Source: metadata/assumptions-ledger.md
% Regenerate: ./build.sh or python3 scripts/generate_assumptions_appendix.py
"""

APPENDIX_MARKER = "## Appendix index"
CHAPTER_ID_RE = re.compile(r"^(ch\d+b?)$")


def load_chapter_labels() -> dict[str, str]:
    labels: dict[str, str] = {}
    for path in sorted(CHAPTERS_DIR.glob("ch*.tex")):
        match = re.match(r"(ch\d+b?)", path.stem)
        if not match:
            continue
        chapter_id = match.group(1)
        text = path.read_text(encoding="utf-8")
        label_match = re.search(r"\\label\{(ch:[^}]+)\}", text)
        if label_match:
            labels[chapter_id] = label_match.group(1)
    return labels


def latex_escape(text: str) -> str:
    replacements = (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("#", r"\#"),
    )
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def parse_table_row(line: str) -> list[str] | None:
    if not line.startswith("|"):
        return None
    cells = [cell.strip() for cell in line.strip("|").split("|")]
    if not cells or cells[0].lower() == "id":
        return None
    if all(set(cell) <= {"-", ":"} for cell in cells):
        return None
    return cells


def source_ref(home: str, labels: dict[str, str]) -> str:
    home = home.strip()
    if home.lower() == "appi":
        return r"Appendix~\ref{appi-lean-proof-spine}"
    chapter_match = CHAPTER_ID_RE.match(home.split()[0])
    if not chapter_match:
        raise ValueError(f"Invalid Home column (expected chNN or appI): {home!r}")
    chapter_id = chapter_match.group(1)
    label = labels.get(chapter_id)
    if label is None:
        raise KeyError(f"No \\label found for {chapter_id}")
    return rf"Chapter~\ref{{{label}}}"


def parse_assumption_tables(text: str) -> list[tuple[str, list[tuple[str, str, str]]]]:
    if APPENDIX_MARKER not in text:
        raise ValueError(f"Missing {APPENDIX_MARKER!r} in {LEDGER_MD}")

    appendix = text.split(APPENDIX_MARKER, 1)[1]
    sections: list[tuple[str, list[tuple[str, str, str]]]] = []
    current_title: str | None = None
    current_rows: list[tuple[str, str, str]] = []

    for line in appendix.splitlines():
        if line.startswith("### "):
            if current_title and current_rows:
                sections.append((current_title, current_rows))
            current_title = line[4:].strip()
            current_rows = []
            continue

        cells = parse_table_row(line)
        if cells is None or current_title is None:
            continue
        if len(cells) < 3:
            raise ValueError(f"Expected ID | Assumption | Home, got: {line!r}")
        entry_id, statement, home = cells[0], cells[1], cells[2]
        current_rows.append((entry_id, statement, home))

    if current_title and current_rows:
        sections.append((current_title, current_rows))

    if not sections:
        raise ValueError("No assumption tables found under Appendix index")

    return sections


def render_section(title: str, rows: list[tuple[str, str, str]], labels: dict[str, str]) -> list[str]:
    lines = [rf"\section{{{latex_escape(title)}}}", r"\begin{description}[style=nextline,leftmargin=2.5em]"]
    for entry_id, statement, home in rows:
        ref = source_ref(home, labels)
        lines.append(rf"\item[\textbf{{{entry_id}}}] {statement} \hfill {ref}")
    lines.append(r"\end{description}")
    lines.append("")
    return lines


def main() -> int:
    try:
        labels = load_chapter_labels()
        sections = parse_assumption_tables(LEDGER_MD.read_text(encoding="utf-8"))
    except (KeyError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    out_lines = [HEADER.rstrip()]
    for title, rows in sections:
        out_lines.extend(render_section(title, rows, labels))

    OUT.write_text("\n".join(out_lines), encoding="utf-8")
    row_count = sum(len(rows) for _, rows in sections)
    print(
        f"Wrote {OUT.relative_to(ROOT)} "
        f"({len(sections)} sections, {row_count} entries)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
