#!/usr/bin/env python3
"""Emit \\nocite{...} for every key cited in manuscript .tex files.

Chapter bibliographies use biblatex refsections; the back-matter
\\printbibliography only lists refsection 0 unless cited keys are also
registered there. This file is \\input before \\printbibliography.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "metadata" / "global-nocite.tex"
CITE_RE = re.compile(r"\\(?:parencite|textcite|cite|autocite|footcite|wikiq)\{([^}]+)\}")

def _keep_cite_key(key: str) -> bool:
    k = key.strip()
    return bool(k) and not k.startswith("#") and k != "bibkey"


def find_citations() -> list[str]:
    cites: set[str] = set()
    for tex in ROOT.rglob("*.tex"):
        if ".venv" in tex.parts:
            continue
        text = tex.read_text(encoding="utf-8", errors="replace")
        for match in CITE_RE.findall(text):
            for key in match.split(","):
                if _keep_cite_key(key):
                    cites.add(key.strip())
    return sorted(cites)


def main() -> None:
    cites = find_citations()
    OUT.write_text(
        "% Auto-generated by scripts/generate_global_nocite.py — do not edit by hand.\n"
        "% Regenerate: make generate or ./scripts/generate_manuscript_tex.sh\n"
        f"\\nocite{{{','.join(cites)}}}\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(cites)} keys).")


if __name__ == "__main__":
    main()
